### ISSUE TITLE
Duplicate Albums with Same Name

### ISSUE THREAD

**Issue by mastermindg** [mopidy/mopidy-local-sqlite#80] opened 2016-05-09 15:16 UTC
I'm scanning my library trying to fix gstreamer detection issues and new songs that are found are placed in a new Album with the same name as the original. These tracks should all be in a single album.

**Comment by tkem** [comment] 2016-05-09 16:28
Currently, album IDs are not determined by album title alone, but by all album-related tags. See #46 for known issues with this. Best results are usually achieved by using a tagger that assigns MusicBrainz IDs.

**Comment by paulhayes** [comment] 2016-06-06 14:32
Yeah, This issue is a bummer for me too, which I'm trying to fix. Which are the album related tags? Once I know them, I can better fix them. Also does calling `mopidyctl local scan` reimport data even if only the id3 has changed?

**Comment by tkem** [comment] 2016-06-06 20:07
@paulhayes: AFAICR `local scan` checks the file's modification date, so updating tags should be sufficient. Album related tags include album name, album artist, track count and volume/disc count.
Especially the last two seem to give issues with multi-disc albums, especially if track count varies by disc (#46).

**Comment by paulhayes** [comment] 2016-06-06 21:25
Is there any way to stop is using volume/disc count in the generation of
the md5?

**Comment by tkem** [comment] 2016-06-07 06:17
@paulhayes: Yes, implement #46 ;-)
So unless there is any *new* information on this subject, e.g. issues *not* related to track/disc number tags, I'm going to close this as a duplicate of #46...

**Closed** 2017-02-17 16:14 UTC
